apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-front
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
        - name: react-front
          image: sachinyaduvanshi7/react-front
          resources:
            limits:
              memory: "356Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-front-service
spec:
  type: ClusterIP
  selector:
    app: react-front
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
