apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: react-front
    app.kubernetes.io/instance: react-front-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: react-front
spec:
  selector:
    app: react-front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
