apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-front
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
        - name: react-front
          image: 597088043946.dkr.ecr.ap-south-1.amazonaws.com/react-front:latest
          resources:
            limits:
              memory: "356Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
